[package]
edition = "2021"
name = "azalea-world"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
azalea-block = {path = "../azalea-block", default-features = false}
azalea-buf = {path = "../azalea-buf"}
azalea-chat = {path = "../azalea-chat"}
azalea-core = {path = "../azalea-core"}
azalea-nbt = {path = "../azalea-nbt"}
log = "0.4.17"
nohash-hasher = "0.2.0"
thiserror = "1.0.32"
uuid = "1.1.2"

[profile.release]
lto = true
